<footer>
<img src="images/Logow.png" alt="LOGO" id="logo_footer">
<div class="footer_cont">
    <h3>Contact us</h3>
    <ul>
    <li>Address: Ha Noi, Viet Nam</li>
    <li>Hotline: +84-123-456-789</li>
    <li>Email: customerservice@hdak.com.vn</li>
    <li>Opening time: 08:00 - 23:00</li>  
    </ul>
</div>
<div class="footer_cont">
    <h3>Financing</h3>
    <ul id="financing">
    <li><a href="page_not_found.php">Apply for Credit  ⇲</a></li>
    <li><a href="page_not_found.php">Make a Payment  ⇲</a></li>
    <li><a href="page_not_found.php">Payment Estimator  ⇲</a></li>
    <li><a href="page_not_found.php">Motorcycle Financing  ⇲</a></li>
    </ul>
</div>
</footer>  