    <nav>
        <img id="nav-logo" src="images/LOGO.png" alt="LOGO">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="product.php">Product</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="enhancements2.php">Enhancements-Part2</a></li>
            <li><a href="manager.php">Manager</a></li>
        </ul>
    </nav>